# Numpy Basics

Welcome to section of Numpy and Pandas. This is the most used Python libraries for data science. NumPy consists of a powerful data structure called multidimensional arrays. Pandas is another powerful Python library that provides fast and easy data analysis platform.

NumPy is a library written for scientific computing and data analysis. It stands for numerical python and also known as array oriented computing.

The most basic object in NumPy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).


 # Why Numpy?
 convenience & speed

 Numpy is much faster than the standard python ways to do computations.

Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

Also, many Numpy operations are implemented in C which is basically being executed behind the scenes, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking. The speed boost depends on which operations you're performing.

 NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

In [ ]:
#array facility

In [1]:
import numpy

In [2]:
numpy.array([1,2,3])

array([1, 2, 3])

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
b = np.array([[1,2,3],[4,5,6]])

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b*4

array([[ 4,  8, 12],
       [16, 20, 24]])

In [20]:
b**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [8]:
b.shape

(2, 3)

In [9]:
a.shape

(3,)

In [10]:
b.dtype

dtype('int64')

In [11]:
b.ndim

2

In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [14]:
[i for i in range(0,51,2)]

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50]

In [ ]:
np.arange(10) #np.arange(start,last-1,skip)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Performance measurement
I mentioned that the key advantages of numpy are convenience and speed of computation.

You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.

In [15]:
c = range(10000)
%timeit [i**3 for i in c]

2.49 ms ± 17.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
c_numpy = np.arange(10000)
%timeit c_numpy**3

23.9 µs ± 936 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Still not convinced? want to see one more intresting example

In [21]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [ ]:
#map,zip,filter,reduce iterator #it is an object in which you can iterate once only.

In [31]:
%timeit list(map(lambda x, y: x*y, l1, l2)) #iterators examples....map zip filters # inerator and iterable..

699 µs ± 6.26 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [32]:
a1 = np.array(l1)
b1 = np.array(l2)

In [ ]:
%timeit a1*b1

8.39 µs ± 177 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
a1

array([       0,        1,        4, ..., 99940009, 99960004, 99980001])

In [ ]:
a1 * a1

array([       0,        1,        4, ..., 99940009, 99960004, 99980001])

so I can do everything without even writing a loop? yes... ohh wao

# Creating Numpy array

There are multiple ways to create numpy array. Lets walk over them

In [ ]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [ ]:
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [ ]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [ ]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.full((3,3),2.2, dtype= np.int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
v = np.array([1,2,3])
np.tile(v,(3,1)) # stack 3 copies of v on top of each other

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [33]:
import random

In [37]:

# between 0 and 1
np.random.random()

0.22595141465214807

In [35]:
# so let say I want a random value between 2 and 50
50*np.random.random()+2

10.886924322254568

In [ ]:
np.random.random([3,3])

array([[ 0.66403971,  0.9379972 ,  0.43803717],
       [ 0.7747613 ,  0.44762134,  0.96971174],
       [ 0.06266723,  0.48139333,  0.7745762 ]])

In [ ]:
# 100 values between 1 and 50
a = np.linspace(1,50,100)#start,last,count

In [ ]:
a

array([  1.        ,   1.49494949,   1.98989899,   2.48484848,
         2.97979798,   3.47474747,   3.96969697,   4.46464646,
         4.95959596,   5.45454545,   5.94949495,   6.44444444,
         6.93939394,   7.43434343,   7.92929293,   8.42424242,
         8.91919192,   9.41414141,   9.90909091,  10.4040404 ,
        10.8989899 ,  11.39393939,  11.88888889,  12.38383838,
        12.87878788,  13.37373737,  13.86868687,  14.36363636,
        14.85858586,  15.35353535,  15.84848485,  16.34343434,
        16.83838384,  17.33333333,  17.82828283,  18.32323232,
        18.81818182,  19.31313131,  19.80808081,  20.3030303 ,
        20.7979798 ,  21.29292929,  21.78787879,  22.28282828,
        22.77777778,  23.27272727,  23.76767677,  24.26262626,
        24.75757576,  25.25252525,  25.74747475,  26.24242424,
        26.73737374,  27.23232323,  27.72727273,  28.22222222,
        28.71717172,  29.21212121,  29.70707071,  30.2020202 ,
        30.6969697 ,  31.19191919,  31.68686869,  32.18

In [ ]:
#memory used by each array element in bytes
a.itemsize

8

In [44]:
np.arange(24).reshape(2,4,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
np.arange(18).reshape(2,3,3) #reshape multiplication should be equal total number

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [ ]:
# -1 will automatically adjust dimention
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

# accessing Numpy array element

In [ ]:
a = np.array([2,4,6,8,10,12,14,16])

In [ ]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
a[2]

6

In [ ]:
a[[2,4,6]]

array([ 6, 10, 14])

In [ ]:
a[2:] #arrayname[start:lastindex-1:skip]start=0,skip=1

array([ 6,  8, 10, 12, 14, 16])

In [ ]:
a[2:5]

array([ 6,  8, 10])

In [ ]:
a[0::2]

array([ 2,  6, 10, 14])

Lets check the same for 2 D array

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[2,2]  #a[start:last-1:skip,start:last-1:skip]

9

In [ ]:
a[:1:,1::]

array([[2, 3]])

In [ ]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [ ]:
a[a > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[(a > 2) & (a < 5)]

array([3, 4])

# subset of numpy array

In [ ]:
a = np.arange(10)

In [ ]:
b = a

In [ ]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b[0] = 11

In [ ]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
# Notice a is also changed
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a=np.arange(10)
b=a.copy()
b[0]=15
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[15  1  2  3  4  5  6  7  8  9]


In [ ]:
np.shares_memory(a,b)

True

In [ ]:
a = np.arange(10)

In [ ]:
b = a.copy()

In [ ]:
b[0] = 11

In [ ]:
b



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.shares_memory(a,b)

False

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# More operations

In [50]:
a = np.array([[1,2,3],[4,5,6]])

In [48]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
b = np.array([[7,8,9],[10,11,12]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a == b

array([[False, False, False],
       [False, False, False]], dtype=bool)

In [53]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# MAthmatical operation

In [ ]:
a = np.arange(1,10)

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [ ]:
np.exp(a)

array([  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
         5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
         1.09663316e+03,   2.98095799e+03,   8.10308393e+03])

In [ ]:
np.sum(a)

45

In [ ]:
np.median(a)

5.0

In [ ]:
a.std()

2.5819888974716112

In [ ]:
a = np.arange(1,10).reshape(3,3)

In [ ]:
np.linalg.det(a)

-9.5161973539299405e-16

In [ ]:
np.linalg.inv(a)

array([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
       [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
       [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])

In [ ]:
np.linalg.eig(a)

(array([  1.61168440e+01,  -1.11684397e+00,  -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b = a.T

In [ ]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.dot(a,b)


array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [55]:
a = np.array([1,1,0], dtype = bool)
b = np.array([1,0,1], dtype = bool)


In [57]:
b

array([ True, False,  True])

In [ ]:
np.logical_or(a,b)

array([ True,  True,  True], dtype=bool)

In [ ]:
np.logical_and(a,b)

array([ True, False, False], dtype=bool)

In [58]:
a==a

array([ True,  True,  True])

In [ ]:
np.all(a == a)

True

In [59]:
a = np.array([[1,2],[3,4]])

In [60]:
a


array([[1, 2],
       [3, 4]])

In [61]:
a.sum()

10

In [ ]:
a.sum(axis=0)

array([4, 6])

In [ ]:
a.sum(axis=1)

array([3, 7])

In [ ]:
a.max()

4

In [ ]:
a.argmax()

3

In [62]:
a=np.array([5,3,9,4])

In [ ]:
a.argmax()

2

In [63]:
a.shape

(4,)

In [ ]:
# model is design to take number of input each of size 10.n input (n,10)
#1 input 10 values (10,)==>(1,10),(10,1)

In [66]:
a[:,np.newaxis].shape # adds a new axis -> 2D

(4, 1)

In [ ]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.argsort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])